apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
    tier: web
    project: test-project
  ports:
  - protocol: TCP
    port:  80 #service port
    targetPort: {{ .Values.configmap.port }} #Target port