kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  labels:
    app: nginx 
    purpose: helm
    tier: web
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: nginx 
      purpose: helm
      tier: web
spec:
  template:
    metadata:
      labels:
        app: nginx 
        purpose: helm
        tier: web
spec:
    spec:
      containers:
      - name: nginx 
        image: nginx:{{ .Values.deployment.imageversion }}