apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx 
    purpose: helm
    tier: web
  ports:
  - protocol: TCP
    port: 80 #service port
    targetPort: {{ .Values.service.port }} #Target port
    nodePort: {{ .Values.configmap.nodePort }}#31786