
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  #deployment related labels
  labels:
    component: frontend 
    project: expense
    tier: web
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      component: frontend 
      project: expense
      tier: web
    #pod definition        
  template:      
    metadata:
      labels:
        component: frontend 
        project: expense
        tier: web
    spec:
      containers:
      - name: frontend
        image: narendranreddy/frontend:{{ .Values.imageVersion }}
        # envFrom:
        # - configMapRef:
        #     name: frontend
        volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true        
      volumes:
       - name: nginx-conf
         configMap:
          name: frontend
          items:
            - key: nginx.conf
              path: nginx.conf